# goal, result and feedback

# Part 1: the goal, to be sent by the client
# The amount of time we want to wait

duration time_to_wait
---

# Part 2: the result, to be sent by the server upon completion
# How much time we waited

duration time_elapsed
uint32 updates_sent # How many updates we provided along the way
---

# Part 3: the feedback, to be sent periodically by the server during execution.
# The amount of time that has elapsed from the start

duration time_elapsed
duration time_remaining # The amount of time remaining until we're done